/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/*
 * Copyright (c) 2025 Renesas Electronics Corporation and/or its affiliates
 * 
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "common_utils.h"
#include "spi_ep.h"
#include "stdbool.h"
#define MODULE_NAME             "r_rspi"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER
/*******************************************************************************************************************//**
 * @addtogroup r_rspi_ep
 * @{
 **********************************************************************************************************************/

/*******************************************************************************************************************//**
 * main() is generated by the RZ Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};
    unsigned char rByte[BUFFER_SIZE_DOWN] = {RESET_VALUE};
    uint8_t converted_serial_input = RESET_VALUE;

    /* version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(BANNER);

    /* Initialize SPI driver */
    err = spi_init();

    if (FSP_SUCCESS != err)
    {   /* SPI module init failed */
        APP_PRINT("** SPI INIT FAILED **\r\n\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("** SPI INIT SUCCESSFUL **\r\n\r\n");
    }

    /* Menu for User Selection */
    APP_PRINT("Select from the below Menu options\r\n\r\n");
    APP_PRINT("Press 1 for Write() and Read()\r\n");
    APP_PRINT("Press 2 for WriteRead()\r\n");
    APP_PRINT("Press 3 to Exit\r\n\r\n");

    while (EXIT != converted_serial_input)
    {
    	if (APP_CHECK_DATA)
        {
            APP_READ(rByte);
            converted_serial_input = (uint8_t)atoi((char *)rByte);

            switch (converted_serial_input)
            {
                case WRITE_AND_READ:
                    err = spi_write_and_read ();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** SPI WRITE AND READ Demo failed **\r\n");
                        spi_clean_up();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** SPI WRITE AND READ Demo Successful**\r\n");
                    }
                    break;
                case WRITE_READ:
                    err = spi_write_read ();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** SPI WRITE Demo failed **\r\n");
                        spi_clean_up();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** SPI WRITE AND READ Demo Successful**\r\n");
                    }
                    break;
                case EXIT:
                    err = spi_exit_demo();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** SPI EXIT Demo failed **\r\n");
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** SPI EXIT Demo successful **\r\n\r\n");
                    }
                    break;
                default:
                    /* Menu for User Selection */
                    APP_PRINT("Select from the below Menu options\r\n\r\n");
                    APP_PRINT("Press 1 for Write() and Read()\r\n");
                    APP_PRINT("Press 2 for WriteRead()\r\n");
                    APP_PRINT("Press 3 to Exit\r\n\r\n");
                    break;
            }
            if((WRITE_AND_READ <= converted_serial_input) && (EXIT > converted_serial_input))
            {
                APP_PRINT ("Enter any other key to go back to the main menu\r\n\r\n");
            }
        }

    }

    APP_PRINT("Exiting SPI demo....\r\n\r\n");
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Initialize MMU. */
        R_MMU_Open (&g_mmu_ctrl, &g_mmu_cfg);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}
/*******************************************************************************************************************//**
 * @} (end addtogroup r_rspi_ep)
 **********************************************************************************************************************/